In [1]:
# =====================================================
# RetailPulse
# Feature Engineering
# Author : Gulafsha
# =====================================================

In [2]:
import pandas as pd
import numpy as np

from datetime import timedelta

print("Libraries Loaded Successfully ✅")

Libraries Loaded Successfully ✅

In [3]:
df = pd.read_csv("../data/cleaned_online_retail.csv")

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Month,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,2009-12,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-12,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-12,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,2009-12,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009-12,30.0

In [4]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 504730 entries, 0 to 504729
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      504730 non-null  int64
 1   StockCode    504730 non-null  str
 2   Description  504730 non-null  str
 3   Quantity     504730 non-null  int64
 4   InvoiceDate  504730 non-null  datetime64[us]
 5   Price        504730 non-null  float64
 6   Customer ID  400916 non-null  float64
 7   Country      504730 non-null  str
 8   Month        504730 non-null  str
 9   Revenue      504730 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(2), str(4)
memory usage: 63.7 MB

In [5]:
print(df.shape)

df.head()

df.info()

df.describe()

(504730, 10)
<class 'pandas.DataFrame'>
RangeIndex: 504730 entries, 0 to 504729
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      504730 non-null  int64
 1   StockCode    504730 non-null  str
 2   Description  504730 non-null  str
 3   Quantity     504730 non-null  int64
 4   InvoiceDate  504730 non-null  datetime64[us]
 5   Price        504730 non-null  float64
 6   Customer ID  400916 non-null  float64
 7   Country      504730 non-null  str
 8   Month        504730 non-null  str
 9   Revenue      504730 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(2), str(4)
memory usage: 63.7 MB

,Invoice,Quantity,InvoiceDate,Price,Customer ID,Revenue
count,504730.000000,504730.000000,504730,504730.000000,400916.000000,504730.000000
mean,514494.693751,11.516944,2010-06-28 17:28:36.218374,4.273960,15361.544074,20.351005
min,489434.000000,1.000000,2009-12-01 07:45:00,0.001000,12346.000000,0.001000
25%,501885.250000,1.000000,2010-03-21 14:06:15,1.250000,13985.000000,4.200000
50%,514835.000000,3.000000,2010-07-06 14:25:00,2.100000,15311.000000,10.200000
75%,527280.000000,12.000000,2010-10-15 13:37:00,4.210000,16805.000000,17.700000
max,538171.000000,19152.000000,2010-12-09 20:01:00,25111.090000,18287.000000,25111.090000
std,14438.120668,87.337583,NaN,64.091288,1680.635823,91.509716

In [6]:
print(df.shape)

(504730, 10)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 504730 entries, 0 to 504729
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      504730 non-null  int64
 1   StockCode    504730 non-null  str
 2   Description  504730 non-null  str
 3   Quantity     504730 non-null  int64
 4   InvoiceDate  504730 non-null  datetime64[us]
 5   Price        504730 non-null  float64
 6   Customer ID  400916 non-null  float64
 7   Country      504730 non-null  str
 8   Month        504730 non-null  str
 9   Revenue      504730 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(2), str(4)
memory usage: 63.7 MB

## Time-Based Feature Engineering

Time-based features are extracted from InvoiceDate to identify seasonal,
monthly, quarterly, and weekly purchasing patterns.

In [8]:
# Create time-based features

df["Year"] = df["InvoiceDate"].dt.year
df["Month_Num"] = df["InvoiceDate"].dt.month
df["Month_Name"] = df["InvoiceDate"].dt.month_name()
df["Quarter"] = df["InvoiceDate"].dt.quarter
df["Day"] = df["InvoiceDate"].dt.day
df["Weekday"] = df["InvoiceDate"].dt.day_name()
df["Hour"] = df["InvoiceDate"].dt.hour

# Weekend indicator
df["Is_Weekend"] = df["InvoiceDate"].dt.dayofweek.isin([5, 6]).astype(int)

print("Time-based features created successfully ✅")

Time-based features created successfully ✅

In [9]:
df[
    [
        "InvoiceDate",
        "Year",
        "Month_Num",
        "Month_Name",
        "Quarter",
        "Day",
        "Weekday",
        "Hour",
        "Is_Weekend"
    ]
].head()

,InvoiceDate,Year,Month_Num,Month_Name,Quarter,Day,Weekday,Hour,Is_Weekend
0,2009-12-01 07:45:00,2009,12,December,4,1,Tuesday,7,0
1,2009-12-01 07:45:00,2009,12,December,4,1,Tuesday,7,0
2,2009-12-01 07:45:00,2009,12,December,4,1,Tuesday,7,0
3,2009-12-01 07:45:00,2009,12,December,4,1,Tuesday,7,0
4,2009-12-01 07:45:00,2009,12,December,4,1,Tuesday,7,0

## RFM Feature Engineering

RFM (Recency, Frequency, Monetary) analysis helps identify valuable, loyal,
and at-risk customers based on their purchasing behaviour.

In [10]:
# Create a reference date (1 day after the latest transaction)

snapshot_date = df["InvoiceDate"].max() + pd.Timedelta(days=1)

print("Snapshot Date:", snapshot_date)

Snapshot Date: 2010-12-10 20:01:00

In [11]:
rfm = df.groupby("Customer ID").agg({
    "InvoiceDate": lambda x: (snapshot_date - x.max()).days,
    "Invoice": "nunique",
    "Revenue": "sum"
})

rfm.columns = ["Recency", "Frequency", "Monetary"]

rfm.head()

             Recency  Frequency  Monetary
Customer ID
12346.0          165         11    372.86
12347.0            3          2   1323.32
12348.0           74          1    222.16
12349.0           43          3   2671.14
12351.0           11          1    300.93

In [12]:
rfm.shape

(4312, 3)

In [13]:
rfm.describe()

           Recency    Frequency       Monetary
count  4312.000000  4312.000000    4312.000000
mean     91.171846     4.455705    2040.406712
std      96.860633     8.170213    8911.755977
min       1.000000     1.000000       2.950000
25%      18.000000     1.000000     307.187500
50%      53.000000     2.000000     701.615000
75%     136.000000     5.000000    1714.932500
max     374.000000   205.000000  349164.350000

In [14]:
rfm.head()

             Recency  Frequency  Monetary
Customer ID
12346.0          165         11    372.86
12347.0            3          2   1323.32
12348.0           74          1    222.16
12349.0           43          3   2671.14
12351.0           11          1    300.93

In [15]:
rfm.shape

(4312, 3)

In [16]:
# Customer-level aggregations

customer_features = df.groupby("Customer ID").agg(
    Total_Quantity=("Quantity", "sum"),
    Total_Revenue=("Revenue", "sum"),
    Invoice_Count=("Invoice", "nunique"),
    Unique_Products=("StockCode", "nunique")
)

customer_features.head()

             Total_Quantity  Total_Revenue  Invoice_Count  Unique_Products
Customer ID
12346.0                  70         372.86             11               26
12347.0                 828        1323.32              2               70
12348.0                 373         222.16              1               20
12349.0                 993        2671.14              3               90
12351.0                 261         300.93              1               21

In [17]:
customer_features["Average_Order_Value"] = (
    customer_features["Total_Revenue"]
    / customer_features["Invoice_Count"]
)

customer_features.head()

,Total_Quantity,Total_Revenue,Invoice_Count,Unique_Products,Average_Order_Value
Customer ID,,,,,
12346.0,70,372.86,11,26,33.896364
12347.0,828,1323.32,2,70,661.660000
12348.0,373,222.16,1,20,222.160000
12349.0,993,2671.14,3,90,890.380000
12351.0,261,300.93,1,21,300.930000

In [18]:
rfm = rfm.merge(
    customer_features,
    left_index=True,
    right_index=True
)

rfm.head()

,Recency,Frequency,Monetary,Total_Quantity,Total_Revenue,Invoice_Count,Unique_Products,Average_Order_Value
Customer ID,,,,,,,,
12346.0,165,11,372.86,70,372.86,11,26,33.896364
12347.0,3,2,1323.32,828,1323.32,2,70,661.660000
12348.0,74,1,222.16,373,222.16,1,20,222.160000
12349.0,43,3,2671.14,993,2671.14,3,90,890.380000
12351.0,11,1,300.93,261,300.93,1,21,300.930000

In [19]:
rfm.info()

<class 'pandas.DataFrame'>
Index: 4312 entries, 12346.0 to 18287.0
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Recency              4312 non-null   int64
 1   Frequency            4312 non-null   int64
 2   Monetary             4312 non-null   float64
 3   Total_Quantity       4312 non-null   int64
 4   Total_Revenue        4312 non-null   float64
 5   Invoice_Count        4312 non-null   int64
 6   Unique_Products      4312 non-null   int64
 7   Average_Order_Value  4312 non-null   float64
dtypes: float64(3), int64(5)
memory usage: 303.2 KB

In [20]:
rfm.isnull().sum()

Recency                0
Frequency              0
Monetary               0
Total_Quantity         0
Total_Revenue          0
Invoice_Count          0
Unique_Products        0
Average_Order_Value    0
dtype: int64

In [21]:
rfm.describe().round(2)

,Recency,Frequency,Monetary,Total_Quantity,Total_Revenue,Invoice_Count,Unique_Products,Average_Order_Value
count,4312.00,4312.00,4312.00,4312.00,4312.00,4312.00,4312.00,4312.00
mean,91.17,4.46,2040.41,1280.05,2040.41,4.46,63.65,376.37
std,96.86,8.17,8911.76,6457.93,8911.76,8.17,85.76,492.36
min,1.00,1.00,2.95,1.00,2.95,1.00,1.00,2.95
25%,18.00,1.00,307.19,156.00,307.19,1.00,17.00,179.49
50%,53.00,2.00,701.62,380.00,701.62,2.00,38.00,285.05
75%,136.00,5.00,1714.93,992.00,1714.93,5.00,79.25,421.48
max,374.00,205.00,349164.35,220600.00,349164.35,205.00,1741.00,11880.84

In [24]:
# Save customer features
rfm.to_csv("../data/customer_features.csv", index=False)

print("✅ customer_features.csv saved successfully!")

# Save RFM features (for Notebook 04)
rfm.to_csv("../data/rfm_features.csv", index=False)

print("✅ rfm_features.csv saved successfully!")

✅ customer_features.csv saved successfully!
✅ rfm_features.csv saved successfully!

In [25]:
rfm.columns.tolist()

['Recency',
 'Frequency',
 'Monetary',
 'Total_Quantity',
 'Total_Revenue',
 'Invoice_Count',
 'Unique_Products',
 'Average_Order_Value']

In [26]:
df = pd.read_csv("../data/customer_features.csv")
print(df.columns.tolist())

['Recency', 'Frequency', 'Monetary', 'Total_Quantity', 'Total_Revenue', 'Invoice_Count', 'Unique_Products', 'Average_Order_Value']

In [27]:
print(rfm.head())

print(rfm.index.name)

             Recency  Frequency  Monetary  Total_Quantity  Total_Revenue  \
Customer ID
12346.0          165         11    372.86              70         372.86
12347.0            3          2   1323.32             828        1323.32
12348.0           74          1    222.16             373         222.16
12349.0           43          3   2671.14             993        2671.14
12351.0           11          1    300.93             261         300.93

             Invoice_Count  Unique_Products  Average_Order_Value
Customer ID
12346.0                 11               26            33.896364
12347.0                  2               70           661.660000
12348.0                  1               20           222.160000
12349.0                  3               90           890.380000
12351.0                  1               21           300.930000
Customer ID

In [28]:
# Convert Customer ID index into a normal column

rfm = rfm.reset_index()

# Rename the column
rfm.rename(columns={"Customer ID": "Customer_ID"}, inplace=True)

# Verify the result
rfm.head()

,Customer_ID,Recency,Frequency,Monetary,Total_Quantity,Total_Revenue,Invoice_Count,Unique_Products,Average_Order_Value
0,12346.0,165,11,372.86,70,372.86,11,26,33.896364
1,12347.0,3,2,1323.32,828,1323.32,2,70,661.660000
2,12348.0,74,1,222.16,373,222.16,1,20,222.160000
3,12349.0,43,3,2671.14,993,2671.14,3,90,890.380000
4,12351.0,11,1,300.93,261,300.93,1,21,300.930000

In [30]:
rfm.to_csv(
    "../data/customer_features.csv",
    index=False
)

print("✅ customer_features.csv saved successfully!")

✅ customer_features.csv saved successfully!

In [31]:
# Verify the saved file

test = pd.read_csv("../data/customer_features.csv")

print(test.columns.tolist())

test.head()

['Customer_ID', 'Recency', 'Frequency', 'Monetary', 'Total_Quantity', 'Total_Revenue', 'Invoice_Count', 'Unique_Products', 'Average_Order_Value']

,Customer_ID,Recency,Frequency,Monetary,Total_Quantity,Total_Revenue,Invoice_Count,Unique_Products,Average_Order_Value
0,12346.0,165,11,372.86,70,372.86,11,26,33.896364
1,12347.0,3,2,1323.32,828,1323.32,2,70,661.660000
2,12348.0,74,1,222.16,373,222.16,1,20,222.160000
3,12349.0,43,3,2671.14,993,2671.14,3,90,890.380000
4,12351.0,11,1,300.93,261,300.93,1,21,300.930000

In [32]:
print(rfm.index.name)

None

In [33]:
print(rfm.head())

print(rfm.index.name)

   Customer_ID  Recency  Frequency  Monetary  Total_Quantity  Total_Revenue  \
0      12346.0      165         11    372.86              70         372.86
1      12347.0        3          2   1323.32             828        1323.32
2      12348.0       74          1    222.16             373         222.16
3      12349.0       43          3   2671.14             993        2671.14
4      12351.0       11          1    300.93             261         300.93

   Invoice_Count  Unique_Products  Average_Order_Value
0             11               26            33.896364
1              2               70           661.660000
2              1               20           222.160000
3              3               90           890.380000
4              1               21           300.930000
None

In [34]:
print(rfm.index.name)

None

In [35]:
print(rfm.columns.tolist())

['Customer_ID', 'Recency', 'Frequency', 'Monetary', 'Total_Quantity', 'Total_Revenue', 'Invoice_Count', 'Unique_Products', 'Average_Order_Value']