# RetailPulse – Streamlit Dashboard

## AI-Powered Retail Analytics Dashboard

**Author:** Gulafsha

### Objective

Create an interactive dashboard for RetailPulse to visualize:

- Executive KPIs
- Sales Performance
- Customer Analytics
- Demand Forecast
- Inventory Optimization

### Business Value

- Real-time insights
- Better decision making
- Interactive exploration
- AI-powered analytics

In [1]:
import pandas as pd

print("Libraries Loaded Successfully ✅")

Libraries Loaded Successfully ✅

In [2]:
summary = pd.read_csv("../outputs/revenue_summary.csv")

summary

            Metric         Value
0    Total Revenue  1.027176e+07
1   Total Quantity  5.812947e+06
2     Total Orders  2.095100e+04
3  Total Customers  4.312000e+03
4   Total Products  4.251000e+03

In [3]:
monthly_sales = pd.read_csv("../outputs/monthly_sales.csv")

monthly_sales.head()

     Month     Revenue
0  2009-12  822483.950
1  2010-01  651155.112
2  2010-02  551504.726
3  2010-03  830915.261
4  2010-04  678875.252

In [4]:
top_products = pd.read_csv("../outputs/top_products.csv")

top_products.head()

                          Description    Revenue
0                              Manual  262589.86
1            REGENCY CAKESTAND 3 TIER  169912.76
2  WHITE HANGING HEART T-LIGHT HOLDER  160345.63
3                      DOTCOM POSTAGE  116408.71
4       ASSORTED COLOUR BIRD ORNAMENT   72890.19

In [5]:
top_customers = pd.read_csv("../outputs/top_customers.csv")

top_customers.head()

   Customer ID    Revenue
0      18102.0  349164.35
1      14646.0  248396.50
2      14156.0  196549.74
3      14911.0  152121.22
4      13694.0  131443.19

In [6]:
top_countries = pd.read_csv("../outputs/top_countries.csv")

top_countries.head()

          Country      Revenue
0  United Kingdom  8812311.833
1            EIRE   380909.570
2     Netherlands   268784.350
3         Germany   202025.391
4          France   147103.140

In [7]:
inventory = pd.read_csv("../outputs/inventory_optimization.csv")

inventory.head()

,StockCode,Description,Total_Quantity,Total_Revenue,Total_Orders,Average_Daily_Demand,Maximum_Daily_Demand,Safety_Stock,Reorder_Level,Inventory_Status
0,10002,INFLATABLE POLITICAL GLOBE,7971,6333.76,310,25.879870,400,4200.0,181.159091,Healthy
1,10002R,ROBOT PENCIL SHARPNER,4,20.57,3,1.333333,2,21.0,9.333333,Restock Soon
2,10080,GROOVY CACTUS INFLATABLE,12,10.20,5,2.400000,6,63.0,16.800000,Restock Soon
3,10109,BENDY COLOUR PENCILS,4,1.68,1,4.000000,4,42.0,28.000000,Restock Soon
4,10120,DOGGY RUBBER,487,105.57,47,10.361702,60,630.0,72.531915,Healthy

In [8]:
forecast = pd.read_csv("../outputs/demand_forecast.csv")

forecast.head()

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,weekly,weekly_lower,weekly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2009-12-01,28570.420043,19005.958600,52332.314070,28570.420043,28570.420043,7366.077179,7366.077179,7366.077179,7366.077179,7366.077179,7366.077179,0.0,0.0,0.0,35936.497222
1,2009-12-02,28540.080630,14490.848375,47586.455403,28540.080630,28540.080630,2456.728277,2456.728277,2456.728277,2456.728277,2456.728277,2456.728277,0.0,0.0,0.0,30996.808907
2,2009-12-03,28509.741217,22319.385140,55752.083065,28509.741217,28509.741217,9734.176894,9734.176894,9734.176894,9734.176894,9734.176894,9734.176894,0.0,0.0,0.0,38243.918111
3,2009-12-04,28479.401804,13022.706503,45942.546353,28479.401804,28479.401804,343.722258,343.722258,343.722258,343.722258,343.722258,343.722258,0.0,0.0,0.0,28823.124062
4,2009-12-05,28449.062391,-5862.933337,27973.347827,28449.062391,28449.062391,-17956.027635,-17956.027635,-17956.027635,-17956.027635,-17956.027635,-17956.027635,0.0,0.0,0.0,10493.034755

In [9]:
summary = pd.read_csv("../outputs/revenue_summary.csv")
monthly = pd.read_csv("../outputs/monthly_sales.csv")
products = pd.read_csv("../outputs/top_products.csv")
customers = pd.read_csv("../outputs/top_customers.csv")
countries = pd.read_csv("../outputs/top_countries.csv")
forecast = pd.read_csv("../outputs/demand_forecast.csv")

print("All files loaded successfully ✅")

All files loaded successfully ✅

In [10]:
summary.head()

            Metric         Value
0    Total Revenue  1.027176e+07
1   Total Quantity  5.812947e+06
2     Total Orders  2.095100e+04
3  Total Customers  4.312000e+03
4   Total Products  4.251000e+03

In [11]:
monthly.head()

     Month     Revenue
0  2009-12  822483.950
1  2010-01  651155.112
2  2010-02  551504.726
3  2010-03  830915.261
4  2010-04  678875.252

In [12]:
products.head()

                          Description    Revenue
0                              Manual  262589.86
1            REGENCY CAKESTAND 3 TIER  169912.76
2  WHITE HANGING HEART T-LIGHT HOLDER  160345.63
3                      DOTCOM POSTAGE  116408.71
4       ASSORTED COLOUR BIRD ORNAMENT   72890.19

In [13]:
customers.head()

   Customer ID    Revenue
0      18102.0  349164.35
1      14646.0  248396.50
2      14156.0  196549.74
3      14911.0  152121.22
4      13694.0  131443.19

In [14]:
countries.head()

          Country      Revenue
0  United Kingdom  8812311.833
1            EIRE   380909.570
2     Netherlands   268784.350
3         Germany   202025.391
4          France   147103.140

In [15]:
forecast.head()

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,weekly,weekly_lower,weekly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2009-12-01,28570.420043,19005.958600,52332.314070,28570.420043,28570.420043,7366.077179,7366.077179,7366.077179,7366.077179,7366.077179,7366.077179,0.0,0.0,0.0,35936.497222
1,2009-12-02,28540.080630,14490.848375,47586.455403,28540.080630,28540.080630,2456.728277,2456.728277,2456.728277,2456.728277,2456.728277,2456.728277,0.0,0.0,0.0,30996.808907
2,2009-12-03,28509.741217,22319.385140,55752.083065,28509.741217,28509.741217,9734.176894,9734.176894,9734.176894,9734.176894,9734.176894,9734.176894,0.0,0.0,0.0,38243.918111
3,2009-12-04,28479.401804,13022.706503,45942.546353,28479.401804,28479.401804,343.722258,343.722258,343.722258,343.722258,343.722258,343.722258,0.0,0.0,0.0,28823.124062
4,2009-12-05,28449.062391,-5862.933337,27973.347827,28449.062391,28449.062391,-17956.027635,-17956.027635,-17956.027635,-17956.027635,-17956.027635,-17956.027635,0.0,0.0,0.0,10493.034755